name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Decode certificate
        run: |
          echo "${{ secrets.CSC_KEY_BASE64 }}" | base64 --decode --ignore-garbage > key.p12

          echo "Certificate decoded and saved as key.p12"

      - name: Publish releases
        env:
          CSC_LINK: key.p12
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win
